version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    networks:
      - speckit-network

  # Example additional service for testing
  test-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: speckit
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: speckit_test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - speckit-network
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  speckit-network:
    driver: bridge